### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by dzienisz**
Start to make some cleanups. I think that it will be better to start new project in https://github.com/facebook/create-react-app. Web development move so fast (babel 7, webpack 4) that it make no sense to refactor the whole app.

### CODE REVIEW

**Comment by lechup** [comment]
Definately agree. Do You manage to update docker image to actually support create-react-app?

**Review by lechup — APPROVED** [review]
:+1:

**Comment by dzienisz** [comment]
It shouldn't be a problem but I'm not a docker expert so it will take some time - https://mherman.org/blog/dockerizing-a-react-app/

I will keep this repo as a reference to the new project.

**Comment by lechup** [comment]
@dzienisz ok, just ping me when project will be ready. I'll make a PR in case docker setup need one, then we simply update this repo with Your code

**Pull request merged**
